name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.1'
      - name: Start Hugo server
        run: hugo serve &
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install package
        run: pip install .
        working-directory: ./test-suite
      - name: Run tests
        run: pytest
        env:
          HUGO_URL: http://localhost:1313
        working-directory: ./test-suite